import Navigation from "../components/navigation/Navigation"
import { Metadata } from "next"

export const metadata: Metadata = {
  title: "Privacy Policy - DeepFakeAI",
  description: "Learn how DeepFakeAI respects your privacy, handles uploaded and submitted media, and protects your information.",
}

export default function PrivacyPolicyPage() {
  return (
    <Navigation>
      <main className="grow mx-auto px-6 py-10 max-w-4xl text-gray-200">
        <div className="border-b border-gray-700 pb-6 mb-8">
          <h1 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">Privacy Policy</h1>
          <p className="text-sm text-gray-400 mt-2">Last updated: September 2026</p>
        </div>

        <div className="space-y-8 leading-relaxed">
          <section className="bg-gray-800/60 border border-gray-700 rounded-xl p-6">
            <h2 className="text-xl font-bold text-lime-400 mb-3">1. Our Commitment to Privacy</h2>
            <p className="text-gray-300">
              DeepFakeAI operates as a public-benefit, independent deepfake detection platform. We are dedicated to
              protecting your privacy and ensuring transparency regarding how data and submitted media are analyzed and stored.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">2. Information We Collect</h2>
            <p className="text-gray-300">
              When using our services, we collect minimal data necessary to fulfill authenticity analysis:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-300 ml-2">
              <li><strong className="text-white">Submitted Media &amp; URLs:</strong> Social media links (X, TikTok, Instagram, Reddit, YouTube) or files you submit for deepfake evaluation.</li>
              <li><strong className="text-white">Technical Metadata:</strong> Media metadata extracted for model inference, such as file format, resolution, audio tracks, and facial bounding boxes.</li>
              <li><strong className="text-white">Analysis Results:</strong> Output scores and detection rationales generated by our ensemble detection models.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">3. How Your Data Is Used</h2>
            <p className="text-gray-300">
              We process media solely for the purpose of detecting AI manipulation and improving detection accuracy:
            </p>
            <ul className="list-disc list-inside space-y-2 text-gray-300 ml-2">
              <li>Running media through image, video, and audio deepfake detectors.</li>
              <li>Compiling confidence scores and detection insights for the verification dashboard.</li>
              <li>Preventing abuse, malicious queries, and automated scraping of the service.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">4. Data Retention &amp; Security</h2>
            <p className="text-gray-300">
              Media submitted for verification is retained securely in our Supabase infrastructure with restricted access.
              We apply industry-standard encryption in transit (HTTPS/TLS) and at rest. We never sell, monetize, or license your personal information to third parties.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-xl font-bold text-white">5. Cookies &amp; Local Storage</h2>
            <p className="text-gray-300">
              DeepFakeAI uses browser local storage strictly to remember your recent verification queries locally on your device. We do not use third-party tracking or advertising cookies.
            </p>
          </section>

          <section className="border-t border-gray-700 pt-6">
            <h2 className="text-xl font-bold text-white mb-2">6. Contact Us</h2>
            <p className="text-gray-300">
              If you have any questions or concerns regarding our privacy practices, reach out via our internal{" "}
              <a href="/contact" className="text-lime-400 hover:underline font-semibold">Help &amp; Contact page</a>.
            </p>
          </section>
        </div>
      </main>
    </Navigation>
  )
}
